### ISSUE TITLE
Clear form

### ISSUE THREAD

**Issue by kaw2k** [willowtreeapps/react-formable#10]
It seems like people care about the ability to quickly clear forms. I don't think this would be a default form thing, but we can easily build higher level forms to take care of this. Especially with #4, passing down values and what not is trivial.

**Comment by uttrasey** [comment]
could we not get by with 

```
<input type="reset" value="Reset" />
```

**Comment by kaw2k** [comment]
That is interesting @uttrasey, we would have to test it out. It wouldn't work with super custom inputs, but would work fine for your normal inputs.

**Comment by kaw2k** [comment]
Closing this, type="reset" works fine.
