### ISSUE TITLE
onSubmit does not show field errors

### ISSUE THREAD

**Issue by kaw2k** [willowtreeapps/react-formable#6]
@oconn brought up an interesting point. Should we by default show field errors when forms are submitted? It could easily be written as a high order component, or a prop to the form. It is a sensible default. The only hesitation I have is `showFieldErrors` allows users to show a subset of errors (which is an edge case). Automatically showing errors removes that option from the users hands as the errors will automatically be shown.

**Comment by glortho** [comment]
1 vote for showing by default but providing option to disable in favor of more granular control with `showFieldErrors`.

**Comment by kaw2k** [comment]
Going to move forward with this. `Form`s default to showing field errors `onSubmit` and you can opt out by passing `suppressFieldErrorsOnSubmit` to the `Form`. (Names subject to change).
